# Generated by Django 6.0.6 on 2026-06-30 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="books_read_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Прочитано книг"),
        ),
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("following", "Подписан"),
                            ("friends", "Друзья"),
                            ("blocked", "Заблокирован"),
                        ],
                        default="following",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Подписчик",
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Подписан",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
                "db_table": "users_friendship",
                "indexes": [
                    models.Index(
                        fields=["follower", "following"],
                        name="users_frien_followe_14d5b4_idx",
                    ),
                    models.Index(
                        fields=["status"], name="users_frien_status_48e94b_idx"
                    ),
                ],
                "unique_together": {("follower", "following")},
            },
        ),
    ]
