# Generated by Django 6.0.6 on 2026-06-30 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="Только буквы и цифры (латиница)",
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z0-9]+$",
                        "Username может содержать только буквы и цифры (латиница).",
                    )
                ],
                verbose_name="Username",
            ),
        ),
    ]
