# Generated by Django 6.0.6 on 2026-06-30 18:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("book", "Книга"),
                            ("movie", "Фильм"),
                            ("painting", "Картина"),
                            ("music", "Музыка"),
                            ("article", "Статья"),
                        ],
                        max_length=20,
                        verbose_name="Тип контента",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="covers/",
                        verbose_name="Обложка/Постер",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Рейтинг",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1000),
                            django.core.validators.MaxValueValidator(2026),
                        ],
                        verbose_name="Год выпуска",
                    ),
                ),
                ("genre", models.CharField(max_length=100, verbose_name="Жанр")),
                (
                    "country",
                    models.CharField(blank=True, max_length=100, verbose_name="Страна"),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="Просмотры"),
                ),
                (
                    "hours_to_read",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Часов на изучение/просмотр"
                    ),
                ),
                (
                    "brief_summary",
                    models.TextField(blank=True, verbose_name="Краткий пересказ/сюжет"),
                ),
                ("review", models.TextField(blank=True, verbose_name="Рецензия")),
                (
                    "ideas",
                    models.TextField(blank=True, verbose_name="Идеи из произведения"),
                ),
                (
                    "interesting_facts",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Массив объектов {title: 'Заголовок', fact: 'Текст факта'}",
                        verbose_name="Интересные факты",
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Специфичные поля для разных типов контента",
                        verbose_name="Дополнительные данные",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Контент",
                "verbose_name_plural": "Контент",
                "db_table": "content_content",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type"], name="content_con_content_5aa5f4_idx"
                    ),
                    models.Index(fields=["title"], name="content_con_title_98e420_idx"),
                    models.Index(fields=["genre"], name="content_con_genre_789d2f_idx"),
                    models.Index(
                        fields=["country"], name="content_con_country_21ffdd_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="characters/",
                        verbose_name="Фото/Портрет",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Фамилия"
                    ),
                ),
                ("about", models.TextField(blank=True, verbose_name="О персонаже")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characters",
                        to="content.content",
                        verbose_name="Контент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Персонаж",
                "verbose_name_plural": "Персонажи",
                "db_table": "content_character",
                "ordering": ["first_name"],
            },
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="Вопрос")),
                (
                    "options",
                    models.JSONField(
                        default=list,
                        help_text="Массив строк с вариантами ответов",
                        verbose_name="Варианты ответов",
                    ),
                ),
                (
                    "correct_answer",
                    models.PositiveSmallIntegerField(
                        verbose_name="Правильный ответ (индекс в options)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_questions",
                        to="content.content",
                        verbose_name="Контент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос теста",
                "verbose_name_plural": "Вопросы теста",
                "db_table": "content_quiz_question",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Оценка (1-10)",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст отзыва")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="content.content",
                        verbose_name="Контент",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "db_table": "content_review",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[("like", "Лайк"), ("dislike", "Дизлайк")],
                        max_length=10,
                        verbose_name="Тип реакции",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="content.review",
                        verbose_name="Отзыв",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_review_reactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Реакция на отзыв",
                "verbose_name_plural": "Реакции на отзывы",
                "db_table": "content_review_reaction",
            },
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["content", "user"], name="content_rev_content_f38a17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["rating"], name="content_rev_rating_93ed14_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("content", "user")},
        ),
        migrations.AddIndex(
            model_name="reviewreaction",
            index=models.Index(
                fields=["review", "user"], name="content_rev_review__ab06e0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reviewreaction",
            unique_together={("review", "user")},
        ),
    ]
