# Generated by Django 6.0.6 on 2026-06-30 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="reviewreaction",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="content.review",
                verbose_name="Отзыв",
            ),
        ),
        migrations.AddField(
            model_name="reviewreaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_review_reactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["content", "user"], name="content_rev_content_f38a17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["rating"], name="content_rev_rating_93ed14_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("content", "user")},
        ),
        migrations.AddIndex(
            model_name="reviewreaction",
            index=models.Index(
                fields=["review", "user"], name="content_rev_review__ab06e0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reviewreaction",
            unique_together={("review", "user")},
        ),
    ]
