# Generated by Django 6.0.6 on 2026-07-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Фамилия"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="people/", verbose_name="Фото"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "date_of_death",
                    models.DateField(blank=True, null=True, verbose_name="Дата смерти"),
                ),
                (
                    "birth_country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Страна рождения"
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        choices=[
                            ("writer", "Писатель"),
                            ("director", "Режиссёр"),
                            ("artist", "Художник"),
                            ("composer", "Композитор"),
                            ("actor", "Актёр"),
                            ("other", "Другое"),
                        ],
                        max_length=20,
                        verbose_name="Профессия",
                    ),
                ),
                ("biography", models.TextField(blank=True, verbose_name="Биография")),
                (
                    "interesting_facts",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Массив объектов {title: 'Заголовок', fact: 'Текст факта'}",
                        verbose_name="Интересные факты",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Человек",
                "verbose_name_plural": "Люди",
                "db_table": "content_person",
                "ordering": ["last_name", "first_name"],
                "indexes": [
                    models.Index(
                        fields=["last_name", "first_name"],
                        name="content_per_last_na_7ad248_idx",
                    ),
                    models.Index(
                        fields=["occupation"], name="content_per_occupat_446efe_idx"
                    ),
                ],
            },
        ),
    ]
