# Generated by Django 6.0.6 on 2026-07-01 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_person"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="courses/",
                        verbose_name="Обложка",
                    ),
                ),
                ("topic", models.CharField(max_length=100, verbose_name="Тема")),
                (
                    "authors",
                    models.JSONField(
                        default=list,
                        help_text="Массив строк с именами авторов",
                        verbose_name="Авторы",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
                "db_table": "content_course",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["topic"], name="content_cou_topic_52b8cf_idx"),
                    models.Index(fields=["title"], name="content_cou_title_6f32e8_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название урока"),
                ),
                ("content", models.TextField(verbose_name="Содержание урока")),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Длительность (в минутах)"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="content.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
                "db_table": "content_lesson",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="LessonQuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="Вопрос")),
                (
                    "options",
                    models.JSONField(
                        default=list,
                        help_text="Массив строк с вариантами ответов",
                        verbose_name="Варианты ответов",
                    ),
                ),
                (
                    "correct_answer",
                    models.PositiveSmallIntegerField(
                        verbose_name="Правильный ответ (индекс в options)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_questions",
                        to="content.lesson",
                        verbose_name="Урок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос теста урока",
                "verbose_name_plural": "Вопросы теста урока",
                "db_table": "content_lesson_quiz_question",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["course", "order"], name="content_les_course__6ba9ac_idx"
            ),
        ),
    ]
