# Generated by Django 6.0.6 on 2026-06-29 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Полное название книги",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        help_text="ФИО автора", max_length=255, verbose_name="Автор"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Страна происхождения",
                        max_length=100,
                        verbose_name="Страна",
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        help_text="Основной жанр книги",
                        max_length=100,
                        verbose_name="Жанр",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        help_text="Год первого издания",
                        validators=[
                            django.core.validators.MinValueValidator(1000),
                            django.core.validators.MaxValueValidator(2026),
                        ],
                        verbose_name="Год издания",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Краткое описание содержания", verbose_name="Описание"
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Рейтинг от 0 до 10",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Рейтинг",
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        help_text="Путь к изображению обложки (covers/cover1.png)",
                        null=True,
                        upload_to="covers/",
                        verbose_name="Обложка",
                    ),
                ),
                (
                    "review",
                    models.TextField(
                        blank=True,
                        help_text="Развернутая рецензия на книгу",
                        verbose_name="Рецензия",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Отображать книгу на сайте",
                        verbose_name="Активно",
                    ),
                ),
            ],
            options={
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["name"], name="books_book_name_fbe345_idx"),
                    models.Index(
                        fields=["author"], name="books_book_author_b941fe_idx"
                    ),
                    models.Index(fields=["genre"], name="books_book_genre_4a7cdf_idx"),
                ],
            },
        ),
    ]
