# Generated by Django 6.0.6 on 2026-06-30 16:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("author", models.CharField(max_length=255, verbose_name="Автор")),
                (
                    "country",
                    models.CharField(blank=True, max_length=100, verbose_name="Страна"),
                ),
                ("genre", models.CharField(max_length=100, verbose_name="Жанр")),
                (
                    "year",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1000),
                            django.core.validators.MaxValueValidator(2026),
                        ],
                        verbose_name="Год издания",
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.0,
                        max_digits=3,
                        verbose_name="Средний рейтинг",
                    ),
                ),
                (
                    "interesting_facts",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Массив объектов {title: 'Заголовок', fact: 'Текст факта'}",
                        verbose_name="Интересные факты",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Рейтинг",
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="covers/",
                        verbose_name="Обложка",
                    ),
                ),
                (
                    "ideas",
                    models.TextField(
                        blank=True,
                        help_text="Что можно вынести из этой книги (опционально)",
                        verbose_name="Идеи из книги",
                    ),
                ),
                ("review", models.TextField(blank=True, verbose_name="Рецензия")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="Просмотры"),
                ),
                (
                    "hours_to_read",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Примерное количество часов на чтение книги",
                        verbose_name="Часов на чтение",
                    ),
                ),
                (
                    "brief_summary",
                    models.TextField(
                        blank=True,
                        help_text="Краткое содержание книги (опционально)",
                        verbose_name="Краткий пересказ сюжета",
                    ),
                ),
            ],
            options={
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
                "db_table": "books_book",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["name"], name="books_book_name_fbe345_idx"),
                    models.Index(
                        fields=["author"], name="books_book_author_b941fe_idx"
                    ),
                    models.Index(fields=["genre"], name="books_book_genre_4a7cdf_idx"),
                    models.Index(
                        fields=["country"], name="books_book_country_9fbee2_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="characters/",
                        verbose_name="Фото героя",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Фамилия"
                    ),
                ),
                ("about", models.TextField(blank=True, verbose_name="О герое")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characters",
                        to="books.book",
                        verbose_name="Книга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Герой",
                "verbose_name_plural": "Герои",
                "db_table": "books_character",
                "ordering": ["first_name"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Оценка (1-10)",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст отзыва")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="books.book",
                        verbose_name="Книга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "db_table": "books_review",
                "ordering": ["-created_at"],
            },
        ),
    ]
