# Generated by Django 6.0.6 on 2026-06-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="book",
            name="books_book_name_fbe345_idx",
        ),
        migrations.RemoveIndex(
            model_name="book",
            name="books_book_author_b941fe_idx",
        ),
        migrations.RemoveIndex(
            model_name="book",
            name="books_book_genre_4a7cdf_idx",
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="book",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="covers/"),
        ),
        migrations.AlterField(
            model_name="book",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="book",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="book",
            name="rating",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name="book",
            name="review",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="year",
            field=models.IntegerField(),
        ),
    ]
