# Generated by Django 6.0.6 on 2026-06-30 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["book", "user"], name="books_revie_book_id_c4fa17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["rating"], name="books_revie_rating_a07249_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("book", "user")},
        ),
    ]
