# Generated by Django 6.0.6 on 2026-06-30 12:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_book_views_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="characters/",
                        verbose_name="Фото героя",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Фамилия"
                    ),
                ),
                ("about", models.TextField(blank=True, verbose_name="О герое")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Герой",
                "verbose_name_plural": "Герои",
                "db_table": "books_character",
                "ordering": ["first_name"],
            },
        ),
        migrations.AlterModelOptions(
            name="book",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
            },
        ),
        migrations.AddField(
            model_name="book",
            name="brief_summary",
            field=models.TextField(
                blank=True,
                help_text="Краткое содержание книги (опционально)",
                verbose_name="Краткий пересказ сюжета",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="hours_to_read",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Примерное количество часов на чтение книги",
                verbose_name="Часов на чтение",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=255, verbose_name="Автор"),
        ),
        migrations.AlterField(
            model_name="book",
            name="country",
            field=models.CharField(blank=True, max_length=100, verbose_name="Страна"),
        ),
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to="covers/", verbose_name="Обложка"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.CharField(max_length=100, verbose_name="Жанр"),
        ),
        migrations.AlterField(
            model_name="book",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активно"),
        ),
        migrations.AlterField(
            model_name="book",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="book",
            name="rating",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="Рейтинг",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="review",
            field=models.TextField(blank=True, verbose_name="Рецензия"),
        ),
        migrations.AlterField(
            model_name="book",
            name="year",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(2026),
                ],
                verbose_name="Год издания",
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["name"], name="books_book_name_fbe345_idx"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["author"], name="books_book_author_b941fe_idx"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["genre"], name="books_book_genre_4a7cdf_idx"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["country"], name="books_book_country_9fbee2_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="book",
            table="books_book",
        ),
        migrations.AddField(
            model_name="character",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="characters",
                to="books.book",
                verbose_name="Книга",
            ),
        ),
    ]
