# Generated by Django 6.0.6 on 2026-06-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_book_average_rating_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="ideas",
            field=models.TextField(
                blank=True,
                help_text="Что можно вынести из этой книги (опционально)",
                verbose_name="Идеи из книги",
            ),
        ),
    ]
