# Generated by Django 6.0.6 on 2026-06-30 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_book_ideas"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[("like", "Лайк"), ("dislike", "Дизлайк")],
                        max_length=10,
                        verbose_name="Тип реакции",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="books.review",
                        verbose_name="Отзыв",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_reactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Реакция на отзыв",
                "verbose_name_plural": "Реакции на отзывы",
                "db_table": "books_review_reaction",
                "indexes": [
                    models.Index(
                        fields=["review", "user"], name="books_revie_review__5c5e58_idx"
                    )
                ],
                "unique_together": {("review", "user")},
            },
        ),
    ]
