# Generated by Django 6.0.6 on 2026-06-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_reviewreaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="interesting_facts",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Массив объектов {title: 'Заголовок', fact: 'Текст факта'}",
                verbose_name="Интересные факты",
            ),
        ),
    ]
