# Generated by Django 6.0.6 on 2026-06-30 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="ID объекта")),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("like", "Лайк"),
                            ("dislike", "Дизлайк"),
                            ("favorite", "В избранное"),
                            ("read", "Прочитано"),
                            ("view", "Просмотр"),
                            ("comment_like", "Лайк комментария"),
                            ("comment_dislike", "Дизлайк комментария"),
                        ],
                        max_length=20,
                        verbose_name="Тип взаимодействия",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Текст (для комментариев)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_likes",
                        to="interactions.interaction",
                        verbose_name="Лайк на комментарий",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Тип контента",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="interactions.interaction",
                        verbose_name="Ответ на комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Взаимодействие",
                "verbose_name_plural": "Взаимодействия",
                "db_table": "interactions_interaction",
                "ordering": ["-created_at"],
            },
        ),
    ]
