# Generated by Django 6.0.6 on 2026-06-30 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="ID объекта")),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("like", "Лайк"),
                            ("dislike", "Дизлайк"),
                            ("favorite", "В избранное"),
                            ("read", "Прочитано"),
                            ("view", "Просмотр"),
                        ],
                        max_length=20,
                        verbose_name="Тип взаимодействия",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Текст (для комментариев)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Тип контента",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="interactions.interaction",
                        verbose_name="Ответ на комментарий",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Взаимодействие",
                "verbose_name_plural": "Взаимодействия",
                "db_table": "interactions_interaction",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="interaction_content_45d5a8_idx",
                    ),
                    models.Index(
                        fields=["user", "content_type", "object_id"],
                        name="interaction_user_id_161f09_idx",
                    ),
                    models.Index(
                        fields=["interaction_type"],
                        name="interaction_interac_270663_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="interaction_created_7488ad_idx"
                    ),
                ],
            },
        ),
    ]
