# Generated by Django 6.0.6 on 2026-06-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0002_interaction_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interaction",
            name="interaction_type",
            field=models.CharField(
                choices=[
                    ("like", "Лайк"),
                    ("dislike", "Дизлайк"),
                    ("favorite", "В избранное"),
                    ("read", "Прочитано"),
                    ("view", "Просмотр"),
                    ("comment_like", "Лайк комментария"),
                    ("comment_dislike", "Дизлайк комментария"),
                ],
                max_length=20,
                verbose_name="Тип взаимодействия",
            ),
        ),
    ]
